# Generated by Django 4.1.2 on 2022-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('capital', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Myapp',
        ),
    ]
